### ISSUE TITLE
List<String> serialization issue

### ISSUE THREAD

**Issue by j-garin** [aurae/retrofit-logansquare#20]
Hello.

I started using LoganSquare with Retrofit not long ago and bumped into a List<String> serialization issue.
Here's now i create an instance of API:
```
new Retrofit.Builder()
				.baseUrl(BuildConfig.baseUrl)
				.addConverterFactory(LoganSquareConverterFactory.create())
				.client(client)
				.build()
				.create(API.class)
```
here's the api:
```
	@FormUrlEncoded
	@POST("v1/conversation/{conversationType}/init")
	Call<ConversationResult> initConversation(@Path("conversationType") String conversationType,
	                                          @Field("contacts") List<String> contactIds,
	                                          @Field("account") String accountId);
```
here's my api call:
```
api.initConversation("internal", Arrays.asList(contactId), accountId);
```
but in requestBody instead of an array ["id1", "id2", ...] i see id1, id2, ... separated with a coma
I tried using LoganSquare.serialize(Arrays.asList(id1, id2, ...)) and the result was correct.

Please help me fix this issue. Thank you

**Comment by aurae** [comment]
This looks like the expected behaviour given Retrofit's specifications. When you use `@Field("key") List<String> params`, it will append a key-value pair for each item in `params` and re-use "key" as the key. What would you like the correct output to be?

```java
Arrays.asList("id1") --> "contacts=id1"
Arrays.asList("id1", "id2") --> "contacts=id1&contacts=id2"
```

If you actually only want to have one single `contacts` field in the body, your approach to serialize the array yourself and add it to the method is correct. `LoganSquare.serialize()` will work in this case - alternatively, you could just call `toString()` on your `List`: `Arrays.asList(id1, id2, ...).toString()`.

Please also refer to [the documentation for Retrofit's `@Field` annotation](https://square.github.io/retrofit/2.x/retrofit/retrofit2/http/Field.html).

**Comment by j-garin** [comment]
I want to have 
```contacts=[ "id1", "id2" ]``` is that possible? Logansquare returns exactly what I want when serializing List<String>. Is it possible without converting data before call?

**Comment by j-garin** [comment]
@aurae also I have one question on this call:

**Comment by aurae** [comment]
The LoganSquare converter doesn't take part in converting a `List<String>` for a form-encoded Field. Retrofit invokes the converter for each `String` inside the List, not the list itself. Therefore, you have to convert the data yourself before making the call.
